In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("sample_people_income_dataset.csv")

In [4]:
df.head()

     id   name  age country  gender  income_in_rupees
0  1001    Ira   35   Nepal    Male            622845
1  1002  Ayaan   46   Nepal  Female           1690453
2  1003  Meera   49   India    Male           1140347
3  1004  Arjun   34   India  Female           1619827
4  1005  Kavya   36   Nepal    Male            382845

In [18]:
df2=df.copy()
df2["Tax"]=df2["income_in_rupees"].apply(lambda x: "20%" if x>= 500000 else "10%")

gender_map={"Male":"M", "Female" : "F", "Unknown" : "U"}
df2["gender"]=df2["gender"].map(gender_map)
df2=df2.assign(new_income=df2["income_in_rupees"]*1.5)
df2["country"]=df2["country"].replace("Nepal","China")

In [21]:
df2.columns=["ID","Name","Age","Country","Gender","Income","Tax","New_Income"]

In [26]:
df2.sort_values("Income").reset_index()

    index    ID     Name  Age     Country Gender   Income  Tax  New_Income
0      41  1042    Ayaan   47       India      F   286999  10%    430498.5
1      45  1046   Vihaan   32       India      M   304527  10%    456790.5
2       4  1005    Kavya   36       China      M   382845  10%    574267.5
3      39  1040    Meera   38       India      F   399905  10%    599857.5
4       7  1008     Sara   48       India      M   433473  10%    650209.5
5      28  1029  Reyansh   49       India      M   476198  10%    714297.0
6      42  1043     Diya   47       India      F   521123  20%    781684.5
7      31  1032    Ayaan   29  Bangladesh      M   557809  20%    836713.5
8      30  1031    Kavya   38       India      F   564382  20%    846573.0
9      23  1024     Sara   50       India      M   568807  20%    853210.5
10     37  1038    Aarav   39       India      M   571410  20%    857115.0
11     16  1017     Myra   24  Bangladesh      F   601929  20%    902893.5
12     33  1034    Arjun   25       India      M   602895  20%    904342.5
13      0  1001      Ira   35       China      M   622845  20%    934267.5
14     26  1027    Aarav   31       India      M   636920  20%    955380.0
15     14  1015   Aditya   35       India      F   646091  20%    969136.5
16     25  1026    Aarav   22   Sri Lanka      M   646883  20%    970324.5
17     21  1022    Meera   32   Sri Lanka      F   677269  20%   1015903.5
18     17  1018  Krishna   46       China      F   725235  20%   1087852.5
19     46  1047  Shaurya   43       India      M   745428  20%   1118142.0
20     40  1041   Aadhya   34       India      M   788119  20%   1182178.5
21      9  1010  Reyansh   39  Bangladesh      F   888054  20%   1332081.0
22     38  1039   Vivaan   22       China      F   892004  20%   1338006.0
23     18  1019   Vivaan   35       China      M   903513  20%   1355269.5
24      6  1007     Diya   48       India      F   906779  20%   1360168.5
25     12  1013     Diya   48  Bangladesh      F   977497  20%   1466245.5
26     24  1025   Vivaan   39       India      F  1080384  20%   1620576.0
27     20  1021    Arjun   43   Sri Lanka      F  1091205  20%   1636807.5
28      2  1003    Meera   49       India      M  1140347  20%   1710520.5
29      8  1009    Arjun   30       India      M  1157164  20%   1735746.0
30     29  1030     Riya   45  Bangladesh      M  1228238  20%   1842357.0
31      5  1006  Shaurya   43       India      F  1271460  20%   1907190.0
32     10  1011    Meera   25       India      F  1274673  20%   1912009.5
33     44  1045   Saanvi   37       India      F  1289097  20%   1933645.5
34     47  1048    Kavya   44  Bangladesh      M  1301637  20%   1952455.5
35     27  1028   Vihaan   29       India      M  1431286  20%   2146929.0
36     49  1050    Arjun   45       India      M  1440914  20%   2161371.0
37     13  1014   Ananya   47       India      M  1489021  20%   2233531.5
38     32  1033  Shaurya   42       India      M  1528893  20%   2293339.5
39     11  1012    Aarav   30   Sri Lanka      M  1530565  20%   2295847.5
40     34  1035  Reyansh   44  Bangladesh      M  1603761  20%   2405641.5
41      3  1004    Arjun   34       India      F  1619827  20%   2429740.5
42     15  1016      Ira   34   Sri Lanka      M  1629639  20%   2444458.5
43     22  1023  Krishna   38       India      F  1655317  20%   2482975.5
44      1  1002    Ayaan   46       China      F  1690453  20%   2535679.5
45     19  1020    Aarav   39       India      F  1821853  20%   2732779.5
46     35  1036     Sara   27       India      M  1848608  20%   2772912.0
47     43  1044    Aarav   25       India      F  1887738  20%   2831607.0
48     48  1049     Diya   30       India      M  1925710  20%   2888565.0
49     36  1037    Arjun   24       India      M  1972107  20%   2958160.5

In [28]:
df.head(2)

     id   name  age country  gender  income_in_rupees
0  1001    Ira   35   Nepal    Male            622845
1  1002  Ayaan   46   Nepal  Female           1690453

In [30]:
df.columns=["Name","Age","Country","Gender","Income_in_Rupees","ID"]

In [37]:

df.head(2)

   Name    Age  Country Gender Income_in_Rupees
0  1001    Ira       35  Nepal             Male
1  1002  Ayaan       46  Nepal           Female

In [38]:
df['id']=col

In [39]:
df.head()

   Name    Age  Country Gender Income_in_Rupees       id
0  1001    Ira       35  Nepal             Male   622845
1  1002  Ayaan       46  Nepal           Female  1690453
2  1003  Meera       49  India             Male  1140347
3  1004  Arjun       34  India           Female  1619827
4  1005  Kavya       36  Nepal             Male   382845

In [40]:
df4=pd.read_csv("sample_people_income_dataset.csv")

In [46]:
df4.head(2)

     id   name  age country  gender  income_in_rupees
0  1001    Ira   35   Nepal    Male            622845
1  1002  Ayaan   46   Nepal  Female           1690453

In [47]:
col=df4.pop('id')

In [48]:
df4['id']=col

In [49]:
df4

       name  age     country  gender  income_in_rupees    id
0       Ira   35       Nepal    Male            622845  1001
1     Ayaan   46       Nepal  Female           1690453  1002
2     Meera   49       India    Male           1140347  1003
3     Arjun   34       India  Female           1619827  1004
4     Kavya   36       Nepal    Male            382845  1005
5   Shaurya   43       India  Female           1271460  1006
6      Diya   48       India  Female            906779  1007
7      Sara   48       India    Male            433473  1008
8     Arjun   30       India    Male           1157164  1009
9   Reyansh   39  Bangladesh  Female            888054  1010
10    Meera   25       India  Female           1274673  1011
11    Aarav   30   Sri Lanka    Male           1530565  1012
12     Diya   48  Bangladesh  Female            977497  1013
13   Ananya   47       India    Male           1489021  1014
14   Aditya   35       India  Female            646091  1015
15      Ira   34   Sri Lanka    Male           1629639  1016
16     Myra   24  Bangladesh  Female            601929  1017
17  Krishna   46       Nepal  Female            725235  1018
18   Vivaan   35       Nepal    Male            903513  1019
19    Aarav   39       India  Female           1821853  1020
20    Arjun   43   Sri Lanka  Female           1091205  1021
21    Meera   32   Sri Lanka  Female            677269  1022
22  Krishna   38       India  Female           1655317  1023
23     Sara   50       India    Male            568807  1024
24   Vivaan   39       India  Female           1080384  1025
25    Aarav   22   Sri Lanka    Male            646883  1026
26    Aarav   31       India    Male            636920  1027
27   Vihaan   29       India    Male           1431286  1028
28  Reyansh   49       India    Male            476198  1029
29     Riya   45  Bangladesh    Male           1228238  1030
30    Kavya   38       India  Female            564382  1031
31    Ayaan   29  Bangladesh    Male            557809  1032
32  Shaurya   42       India    Male           1528893  1033
33    Arjun   25       India    Male            602895  1034
34  Reyansh   44  Bangladesh    Male           1603761  1035
35     Sara   27       India    Male           1848608  1036
36    Arjun   24       India    Male           1972107  1037
37    Aarav   39       India    Male            571410  1038
38   Vivaan   22       Nepal  Female            892004  1039
39    Meera   38       India  Female            399905  1040
40   Aadhya   34       India    Male            788119  1041
41    Ayaan   47       India  Female            286999  1042
42     Diya   47       India  Female            521123  1043
43    Aarav   25       India  Female           1887738  1044
44   Saanvi   37       India  Female           1289097  1045
45   Vihaan   32       India    Male            304527  1046
46  Shaurya   43       India    Male            745428  1047
47    Kavya   44  Bangladesh    Male           1301637  1048
48     Diya   30       India    Male           1925710  1049
49    Arjun   45       India    Male           1440914  1050

In [51]:
df5=pd.read_csv("sample_people_income_dataset.csv")

In [54]:
df5.head()

     id   name  age country  gender  income_in_rupees
0  1001    Ira   35   Nepal    Male            622845
1  1002  Ayaan   46   Nepal  Female           1690453
2  1003  Meera   49   India    Male           1140347
3  1004  Arjun   34   India  Female           1619827
4  1005  Kavya   36   Nepal    Male            382845

In [56]:
new_order=[col for col in df5.columns if col!="id"] +["id"]
df5[new_order]

       name  age     country  gender  income_in_rupees    id
0       Ira   35       Nepal    Male            622845  1001
1     Ayaan   46       Nepal  Female           1690453  1002
2     Meera   49       India    Male           1140347  1003
3     Arjun   34       India  Female           1619827  1004
4     Kavya   36       Nepal    Male            382845  1005
5   Shaurya   43       India  Female           1271460  1006
6      Diya   48       India  Female            906779  1007
7      Sara   48       India    Male            433473  1008
8     Arjun   30       India    Male           1157164  1009
9   Reyansh   39  Bangladesh  Female            888054  1010
10    Meera   25       India  Female           1274673  1011
11    Aarav   30   Sri Lanka    Male           1530565  1012
12     Diya   48  Bangladesh  Female            977497  1013
13   Ananya   47       India    Male           1489021  1014
14   Aditya   35       India  Female            646091  1015
15      Ira   34   Sri Lanka    Male           1629639  1016
16     Myra   24  Bangladesh  Female            601929  1017
17  Krishna   46       Nepal  Female            725235  1018
18   Vivaan   35       Nepal    Male            903513  1019
19    Aarav   39       India  Female           1821853  1020
20    Arjun   43   Sri Lanka  Female           1091205  1021
21    Meera   32   Sri Lanka  Female            677269  1022
22  Krishna   38       India  Female           1655317  1023
23     Sara   50       India    Male            568807  1024
24   Vivaan   39       India  Female           1080384  1025
25    Aarav   22   Sri Lanka    Male            646883  1026
26    Aarav   31       India    Male            636920  1027
27   Vihaan   29       India    Male           1431286  1028
28  Reyansh   49       India    Male            476198  1029
29     Riya   45  Bangladesh    Male           1228238  1030
30    Kavya   38       India  Female            564382  1031
31    Ayaan   29  Bangladesh    Male            557809  1032
32  Shaurya   42       India    Male           1528893  1033
33    Arjun   25       India    Male            602895  1034
34  Reyansh   44  Bangladesh    Male           1603761  1035
35     Sara   27       India    Male           1848608  1036
36    Arjun   24       India    Male           1972107  1037
37    Aarav   39       India    Male            571410  1038
38   Vivaan   22       Nepal  Female            892004  1039
39    Meera   38       India  Female            399905  1040
40   Aadhya   34       India    Male            788119  1041
41    Ayaan   47       India  Female            286999  1042
42     Diya   47       India  Female            521123  1043
43    Aarav   25       India  Female           1887738  1044
44   Saanvi   37       India  Female           1289097  1045
45   Vihaan   32       India    Male            304527  1046
46  Shaurya   43       India    Male            745428  1047
47    Kavya   44  Bangladesh    Male           1301637  1048
48     Diya   30       India    Male           1925710  1049
49    Arjun   45       India    Male           1440914  1050